-- Insertar prendas específicas en SQL Server
USE FitStyleDB;
GO

IF NOT EXISTS (SELECT 1 FROM prendas WHERE nombre = 'Polera Terrex Estampada Cuello Redondo')
BEGIN
    INSERT INTO prendas (nombre, descripcion, precio, genero, material, url, url_imagen, tipo_prendas_id_tipo, temporadas_id_temporada, colores_id_color, ocasiones_id_ocasion, marcas_id_marca) VALUES 
    ('Polera Terrex Estampada Cuello Redondo', 'Una polera holgada e informal. Inspirada en los paisajes salvajes y la aventura en la montaña, esta polera adidas Terrex es una prenda versátil que puedes usar en los senderos o mientras planificas tu próxima aventura.', 169.00, 1, '70% algodón, 30% poliéster (reciclado)', 'https://www.adidas.pe/polera-terrex-estampada-cuello-redondo/JX3854.html', 'https://imgur.com/a/rsZMtZU', 1, 1, 8, 1, 1),
    ('Polera Terrex Estampada Cuello Redondo', 'Una polera holgada e informal. Inspirada en los paisajes salvajes y la aventura en la montaña, esta polera adidas Terrex es una prenda versátil que puedes usar en los senderos o mientras planificas tu próxima aventura.', 169.00, 1, '70% algodón, 30% poliéster (reciclado)', 'https://www.adidas.pe/polera-terrex-estampada-cuello-redondo/JX3854.html', 'https://imgur.com/a/xTJKjsQ', 1, 1, 9, 1, 1),
    ('Polera Terrex Estampada Cuello Redondo', 'Una polera holgada e informal. Inspirada en los paisajes salvajes y la aventura en la montaña, esta polera adidas Terrex es una prenda versátil que puedes usar en los senderos o mientras planificas tu próxima aventura.', 169.00, 1, '70% algodón, 30% poliéster (reciclado)', 'https://www.adidas.pe/polera-terrex-estampada-cuello-redondo/JX3854.html', 'https://imgur.com/a/psbX6M2', 1, 1, 12, 1, 1),
    ('Casaca Bómber Térmica Essentials 3 Tiras', 'Una casaca bómber holgada hecha con materiales reciclados. No importa si estás haciendo mandados o encontrándote con amigos, esta casaca bómber de adidas es todo lo que necesitas.', 329.00, 1, '100% poliéster (reciclado)', 'https://www.adidas.pe/casaca-bomber-termica-essentials-3-tiras/JD1294.html', 'https://imgur.com/a/h8qZwar', 2, 1, 2, 1, 1),
    ('Casaca Bómber Térmica Essentials 3 Tiras', 'Una casaca bómber holgada hecha con materiales reciclados. No importa si estás haciendo mandados o encontrándote con amigos, esta casaca bómber de adidas es todo lo que necesitas.', 329.00, 1, '100% poliéster (reciclado)', 'https://www.adidas.pe/casaca-bomber-termica-essentials-3-tiras/JD1294.html', 'https://imgur.com/a/wsCMyKh', 2, 1, 3, 1, 1),
    ('WOVEN TRACKPANT', 'Woven Trackpant es un nuevo producto para Mujer de adidas. Te invitamos a ver las imágenes para apreciar más detalles desde diferentes ángulos.', 379.00, 0, '100% poliéster (reciclado)', 'https://www.adidas.pe/woven-trackpant/JD0087.html', 'https://imgur.com/a/XcEYda1', 6, 2, 5, 1, 1),
    ('Pantalón Jean Cut Slim Fit', 'Tus jeans favoritos hechos en un tejido mucho más cómodo. Nuestro Jean Cut es lo mejor de todos los mundos: fácil de combinar, cómodo y listo para ir a cualquier parte.', 164.25, 1, '37% poliéster', 'https://www.dockers.pe/pantalon-jean-cut-slim-fit-56791-0014/p', 'https://imgur.com/a/mXlFSOf', 7, 3, 1, 3, 5),
    ('Pantalón Mujer Slim Ankle Fit', 'Un pantalón elevado que es perfecto para usar en el trabajo, ya sea en casa o en la oficina. El corte entallado cónico es fácil y favorecedor.', 199.00, 0, '63% Algodón, 35% Poliéster, 2% Elastano', 'https://www.dockers.pe/pantalon-mujer-slim-ankle-fit-a1770-0001/p', 'https://imgur.com/a/npML6G1', 7, 3, 2, 3, 5),
    ('Camisa Signature Comfort Flex Regular Fit', 'Una camisa clásica que se ve apropiada en cualquier ambiente. Está confeccionada con la tecnología Wrinkle Free, lo que significa que lucirás sin arrugas en todo momento.', 134.25, 1, '55% Algodón, 43% Poliéster, 2% Elastano', 'https://www.dockers.pe/camisa-signature-comfort-flex-regular-fit-52661-0000/p', 'https://imgur.com/a/jgGhmBb', 3, 3, 1, 3, 5),
    ('BLUSA FLUID VISCOSE REGULAR SHIRT', 'BLUSA PARA DAMA M/L', 367.92, 0, '98% Algodón Orgánico, 2% Elastano', 'https://pe.tommy.com/blusa-para-dama-m-l-ww0ww43575bds/p', 'https://imgur.com/a/0mHbnTi', 4, 2, 8, 3, 6),
    ('Mini Falda Dionne', 'Minifalda color entero. Pretina embolsada con corte en la cadera. Detalle de cintas con amarre en la parte de la cintura.', 119.90, 0, 'Tela gasa', 'https://now.com.pe/collections/faldas-shorts/products/mini-falda-dionne', 'https://imgur.com/a/zRWtKvv', 8, 2, 8, 1, 7),
    ('Jogger Fit Sommers', 'Jogger cargo. Elasticado en cintura. Pasador de la misma tela. Elasticado en botapie', 129.90, 0, 'Tela chambray', 'https://now.com.pe/collections/pantalones-jeans/products/jogger-fit-sommers', 'https://imgur.com/a/yA5f0AL', 9, 1, 1, 1, 7);
END
GO
